import logging
from typing import List

from app.models.schemas import Message

logger = logging.getLogger("copilot_backend.gemini")


class GeminiClientError(Exception):
    """Raised when an error occurs while communicating with Gemini API."""


class GeminiClient:
    """
    PUBLIC_INTERFACE
    Simple wrapper over Google's Generative AI (Gemini) text generation.
    """

    def __init__(self, api_key: str, model_name: str = "gemini-1.5-flash"):
        """
        Initialize the Gemini client.

        Args:
            api_key: Google Generative AI API key.
            model_name: The Gemini model to use.
        """
        self.api_key = api_key
        self.model_name = model_name

        # Lazy import so the app can still start without the package for non-chat operations
        try:
            import google.generativeai as genai  # type: ignore
        except Exception as e:  # pragma: no cover
            logger.error("google-generativeai package is not installed: %s", e)
            raise GeminiClientError(
                "google-generativeai package is required on the server. Please install dependencies."
            )

        self._genai = genai
        self._genai.configure(api_key=self.api_key)

        try:
            self._model = self._genai.GenerativeModel(self.model_name)
        except Exception as e:
            logger.exception("Failed to initialize Gemini model: %s", e)
            raise GeminiClientError("Failed to initialize Gemini model")

    def generate_reply(self, messages: List[Message]) -> str:
        """
        Generate a reply from Gemini based on the conversation history.

        Args:
            messages: Conversation messages (user and assistant).

        Returns:
            str: The generated reply content.
        """
        # Convert messages to a single prompt for simplicity.
        # You can enhance to use proper structured history if needed.
        conversation = []
        for m in messages:
            prefix = "User" if m.role == "user" else "Assistant"
            conversation.append(f"{prefix}: {m.content}")
        conversation.append("Assistant:")

        prompt = "\n".join(conversation)

        try:
            result = self._model.generate_content(prompt)
            # google-generativeai returns an object with .text attribute for simple responses
            text = getattr(result, "text", None)
            if not text:
                # Try candidates if available
                candidates = getattr(result, "candidates", None)
                if candidates:
                    first = candidates[0]
                    parts = getattr(first, "content", {}).get("parts") if isinstance(getattr(first, "content", None), dict) else None
                    if parts and len(parts) > 0 and "text" in parts[0]:
                        text = parts[0]["text"]
            if not text:
                logger.error("No text returned from Gemini response.")
                raise GeminiClientError("No response generated by the model.")
            return text.strip()
        except Exception as e:
            logger.exception("Error generating content from Gemini: %s", e)
            raise GeminiClientError("Failed to generate content from Gemini.")
